package.json
`vsce` only supports semver strings with digits, `0.4.0-alpha` fails at `vsce publish`
remove pre-release flag so it becomes `0.4.0`
=> correct semver version string to only use digits

languages/ros.msg.configuration.json, languages/syntaxes/ros.msg.tmLanguage.json, package.json
update extension dependencies:
- ROS Message language support for `.msg`, `.srv`, and `.action` files was previously hosted in [`vscode-msg`](https://github.com/ajshort/vscode-msg). Merge into `vscode-ros`
- `vscode-ros` updates configurations referenced by `python` and `cpptools` extensions, declare dependencies on those extensions
=> update extension dependencies

src/extension.ts
check both `devel` and `devel_isolated` for setup script
pick change from https://github.com/ooeygui/vscode-ros/commit/d0f390343a94774a97d27c7e0ef490fff516616f#diff-45327f86d4438556066de133327f4ca2R268 to fix https://github.com/ms-iot/vscode-ros/issues/41
=> check both devel and devel isolated for setup script

package-lock.json, package.json, src/ros/build-env-utils.ts, src/ros/utils.ts
On Windows, the cpp property should be using the following settings:
```
"name": "Windows",
"intelliSenseMode": "msvc-x64",
```
Also, we should not add `/usr/include` when it is Windows.
(This fix should be able to address part of #72.)
=> Update cpp property per platform

templates/preview.html
* To correctly update links' pose, the transform vectors needs to be calculated wrt the world coordinate.
* Use tfClient callbacks instead to update the pose state. (`SceneNode.pose` is captured from `constructor`, but it seems to be just a temp value, and I noticed sometimes it might not be up-to-dated. And `TFClient` has better documented interfaces how to make use of it.)
[1] http://robotwebtools.org/jsdoc/roslibjs/r2/symbols/ROSLIB.TFClient.html
[2] http://robotwebtools.org/jsdoc/ros3djs/r6/SceneNode.js.html
=> [urdf-preview] propagate joint transform wrt the world coordinate

src/ros/core-helper.ts
How to reproduce:
1. Run the `vscode-ros` in development mode.
2. Run `ros.startCore`
3. Run `ros.showCoreStatus`
4. Close core webview panel.
Expected behavior:
No exceptions are thrown from the debug console.
Actual behavior:
`rejected promise not handled within 1 second: Error: Webview is disposed` is keeping show up in debug console.
=> [ros.showCoreStatus] Dispose the polling callbacks when webview closes.

src/ros/core-monitor/main.ts
When `parameters[p]` is a primitive data types, it doesn't have `trim()` defined and it causes exception to call. To avoid that, convert the value to `String` first and then invokes `trim()`.
=> [ros.showCoreStatus] Fix trim() exception when processing parameters

src/extension.ts
Per [`REP 123`](http://www.ros.org/reps/rep-0123.html), `ROS_ROOT` is deprecated. And favor `ROS_DISTRO` which is set in `ROS1` and `ROS2` by [`ros_environment`](https://github.com/ros/ros_environment) to determine what `ROS` release in use.
=> [ros] Use ROS_DISTRO to check ROS environments

src/ros/build-env-utils.ts, src/ros/common/unknown-ros.ts, src/ros/ros.ts, src/ros/ros1/ros1.ts, src/ros/ros2/ros2.ts, src/urdfPreview/preview.ts
* Implemented `getPackages()`. `findPackageLaunchFiles()`, and `activateRoslaunch()` for ROS2, which are required to enable `ros.roslaunch` extension command.
=> [ros2] add support for `ros2 launch`

ci/azure-pipelines.release.yml, ci/azure-pipelines.yml
VS Code uses Node.js `>=10.2.0` since https://code.visualstudio.com/updates/v1_31
the latest VS Code `1.37.1` runs `10.11.0`
*however, this change does not actually affect pipeline since `>=10.x` will still resolve to the latest `10.x` version*
=> use Node.js >=10.2.0

src/ros/ros2/daemon.ts, src/ros/ros2/ros2-monitor.ts, src/ros/ros2/ros2.ts, src/ros/ros2/webview/main.ts
* `ROS2 System Status Webview`: use `xmlrpc` client to mimic [`ros2cli`](https://github.com/ros2/ros2cli/blob/master/ros2cli/ros2cli/daemon/__init__.py) behavior and query the available ROS2 system status. 
* `ROS2 StatusBarItem`:  replace `ros2 daemon status` CLI call with `xmlrpc` method call to query the system readiness, which reduces the overall CPU usage.
=> [ros2] ros2 system status monitor

src/ros/build-env-utils.ts, src/ros/common/unknown-ros.ts, src/ros/ros.ts, src/ros/ros1/ros1.ts, src/ros/ros2/ros2.ts
In this change, I abstracted out `getWorkspaceIncludeDirs` into `rosApi` since ROS1 and ROS2 is using different approaches to get the workspace include directories. And in ROS2, I used `colcon list -p` to get the base paths for packages under a workspace, and add those paths where a `include` subfolder exists.
=> [ros2] Add ros2 support for ros.updateCppProperties

src/debugger/configuration/resolvers/launch.ts
let `vscode-python` pick port automatically so we don't need to take care of the logic
=> let vscode-python pick port automatically

src/debugger/configuration/resolvers/launch.ts
C++ binary and Python scripts are all executable on Linux, to distinguish between these 2, need to check shebang line for the Python script. In this change, we read the first line of the executable and check if it is a shebang pointing to Python, and launch Python/C++ debug sessions based on that check.
also in this change: pass down ROS node names to debug sessions for better readability
=> enable launching C++ and Python binaries on Linux

package.json, src/build-tool/build-tool.ts, src/build-tool/catkin-tools.ts, src/build-tool/catkin.ts, src/extension.ts
* Defined all the task types in `package.json`.
* Dropped the extra (and reserved) `$` prefix from the name of problem matcher. Otherwise, the vscode will be complaining unexpected object types when it is referred in `tasks.json`.
* Removed the unused `target` attribute to avoid VSCode throwing out errors about `Property target is not allowed` when adding tasks in `tasks.json`.
* Register all task providers by correct types.
fix #126, #114
=> Correct task provider usages

src/build-tool/build-tool.ts, src/extension.ts
Source the workspace after a build task ends for convenience. It is useful when there is a change in `devel` space. (For example, in `catkin_make` build, if `bin` was not created at the initial build, but it is created later as you add more code to your project. In such case, you will need to run `devel\setup.bat` again to properly source the environment. Likewise, in `catkin_make_isolated` build, along with more packages added to your workspace, you will need to run `devel_isolated\setup.bat` to exercise newly built isolated packages chain again.)
=> Source the workspace after a ROS build task ends.

src/debugger/configuration/providers/ros.ts
This pull request is to implement `provideDebugConfigurations` so for the first time when developers generate the debug configuration, we will first prompt users what debug types to use (attach or launch) and if it is launch debug, then prompt which package\launch files to use.
=> Improve the first-time UX when adding debug config.

README.md
this fixes https://github.com/ms-iot/vscode-ros/issues/140
=> use absolute link in top-level README.md

.github/workflows/workflow.yml, README.md
- Enabling packaging in CI build.
- VSIX package doesn't like SVG in the README.md, so remove it for now.
=> VSIX package doesn't like the SVG asset.

.vscode/settings.json, src/build-tool/build-tool.ts
The task provider for "catkin_cmake" tasks unexpectedly provided a task of type "catkin_make".
=> bugfix for error:

src/ros/ros1/core-helper.ts, src/ros/ros2/ros2-monitor.ts, src/urdfPreview/preview.ts, templates/preview.html
Since vscode 1.47, the usage of `vscode-resource` will be generating errors and it recommended to migrating to `vscode-webview-resource`. And also now it is recommended to use `https` to access the external resource.
Fixes #261 and #214.
=> updated to use vscode-webview-resource for vscode 1.47

src/ros/ros1/ros1.ts
This fixes issue #184 
It makes the plugin work with catkin build commands, which make use of symbolic links to the executable.
=> Have executable search follow symbolic links

.vscode/settings.json, doc/debug-support.md, package.json, src/build-tool/catkin-tools.ts, src/build-tool/catkin.ts, src/build-tool/colcon.ts, src/build-tool/ros-shell.ts, src/extension.ts
Implements #305
Add args parameter to all build tool tasks that allows customization in the workspaces's tasks.json by users
Implement generic task named `ros`
Add `roscore` and `roslaunch` commands using `ros` task that allows user to run and customize them in tasks.json
=> Allow customization of build tool tasks

src/ros/ros2/ros2.ts
Find any launch file ending with launch.py instead of requiring .launch.py.
This should address https://github.com/ms-iot/vscode-ros/issues/364, but I have not tested it.
=> [ros2] find all launch files

THIRD_PARTY_NOTICE.md, assets/scripts/ros2_launch_dumper.py, package.json, src/debugger/configuration/resolvers/ros1/launch.ts, src/debugger/configuration/resolvers/ros2/launch.ts, src/debugger/manager.ts, src/extension.ts, src/ros/ros2/ros2.ts
* Adding the initial ROS2 Launch Debug support. Current approach is to invoke ROS2 Launch System API and to mimic the entity traversal like [launch_service](https://github.com/ros2/launch/blob/master/launch/launch/launch_service.py).
=> [ROS2] Adding Initial ROS2 Launch Debug Support

src/extension.ts, src/ros/cli.ts, src/ros/ros2/ros2.ts
* Add error messages on exceptions for better diagnosis. It may help when people are reporting issues in future.
* And follow the symlink when searching for ROS2 launch files (we did the same thing for ROS1, and I am keeping the behavior consistent here.)
=> Adding error messages on exceptions for better diagnosis.

src/debugger/configuration/resolvers/ros2/launch.ts
Launch debug args is optional, and we should skip when it is null.
=> Launch debug args is optional.

package-lock.json, package.json, src/extension.ts, src/ros/cli.ts, src/ros/common/unknown-ros.ts, src/ros/ros.ts, src/ros/ros1/ros1.ts, src/ros/ros2/ros2.ts
While exploring #330, I added a command for running rostest files as part of broader support for rostest. Since it seems debugging support is already working, I decided to submit this feature independently. As I'm not familiar with ROS2, this is implemented for just ROS1.
=> Added command for running a ROS test file (ROS1)

src/ros/ros2/ros2.ts
Determine the includeDirs to set in .vscode/c_cpp_properties.json
from AMENT_PREFIX_PATH.
I checked with eloquent and foxy and it worked for both.
Closes #374
=> Use AMENT_PREFIX_PATH instead of COLCON_PREFIX_PATH. Closes #374

src/build-tool/colcon.ts
Fixes running the colcon build task which currently throws
```
> Executing task: colcon --workspace /home/alex/ros2_ws_rclcpp_sub_pub_qos_event build <
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
{build,extension-points,extensions,graph,info,list,metadata,test,test-result,version-check} ...
colcon: error: argument verb_name: invalid choice: '--workspace' (choose from 'build', 'extension-points', 'extensions', 'graph', 'info', 'list', 'metadata', 'test', 'test-result', 'version-check')
The terminal process "/bin/bash '-c', 'colcon --workspace /home/alex/ros2_ws_rclcpp_sub_pub_qos_event build'" terminated with exit code: 2.
```
Presumably this is an copy+paste error introduced in https://github.com/ms-iot/vscode-ros/commit/92f0aec30d76ca4154974219dfe2156fe7c8a515
=> Fix colcon path argument

templates/preview.html
Simply added a hemisphere light to better show features of URDF from all sides. The default ros viewer object includes a directional light that doesn't show the back side of the URDF nicely.
Before:
After:
=> Fix lighting in URDF Preview

src/debugger/configuration/resolvers/ros1/launch.ts, src/debugger/configuration/resolvers/ros2/launch.ts, src/debugger/vscode-cpptools.launch.json.d.ts
Fixes https://github.com/ms-iot/vscode-ros/issues/388
=> Enable pretty printing for GDB.

src/debugger/process-picker/utils.ts
This implementing a fix similar to https://github.com/microsoft/vscode/pull/104277/commits/fc2eb524e1a1a3aa6960e05a82377e36c70b4190 and other plugins that use 'ps'.
=> ignore 'screen size is bogus' ps command error

README.md, src/debugger/configuration/resolvers/ros1/launch.ts, src/debugger/configuration/resolvers/ros2/launch.ts
This change allows you to debug not just your code, but also ROS code if you have external symbols.
=> Enable Symbol path passthrough

package-lock.json, package.json, src/extension.ts, src/ros/build-env-utils.ts
This change updates the C++ properties so that intellisense works better.
Addresses:
* https://github.com/ms-iot/vscode-ros/issues/336
=> Update C++ properties to for intellisense

src/ros/build-env-utils.ts
Use the default workspace storage directory (i.e.  ~/.config/Code/User/workspaceStorage/${workspace ID}/) instead of ${workspaceFolder}/.vscode to avoid performance issues / crashes caused by frequent writes to the .vscode directory which is being watched
Setting browse.databaseFile to an empty string will also instruct vs code to use the default workspace storage directory, but using ${default} has the added benefit that the "C_Cpp.default.browse.databaseFilename" entry in settings.json will be honored if present. 
Ref https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp
Ref https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference
=> Use default cpp browse database filepath

package-lock.json, src/ros/ros2/ros2-monitor.ts
Fixed a problem that prevented connection to daemon if ROS_DOMAIN_ID was set in the environment variable.
closes: #724
before
https://user-images.githubusercontent.com/16977736/170816687-79efa91c-4559-4bff-b4ff-7526c71bfc74.mp4
after
https://user-images.githubusercontent.com/16977736/170816694-ea76e938-7587-4127-a211-2206cde1e903.mp4
=> fix: #724 handle ROS_DOMAIN_ID

src/debugger/configuration/resolvers/attach.ts
Add setupCommands of "-enable-pretty-printing" to show the value of C++ STL containers when in "ros attach" mode.
=> Update attach.js to enable pretty-printing for "ros attach" mode

package.json, src/debugger/configuration/providers/ros.ts, src/debugger/configuration/resolvers/ros2/debug_launch.ts, src/debugger/manager.ts
Implements ROS 2 Launch File debugging!
With this change, you can put breakpoints in a ROS 2 launch file, and have it break.
> NOTE: This change currently only implements the debugging of the file itself - not the launched ROS nodes. That's coming soon.
https://github.com/ms-iot/vscode-ros/issues/567
https://github.com/ms-iot/vscode-ros/issues/710
=> Feature/debug ROS 2 launch files

package-lock.json, package.json, src/urdfPreview/URDFPreviewPanel.ts, src/urdfPreview/preview.ts
This change does the follow:
* Resolves a rotation order issue, which resulted in some operations rendering incorrectly
* Adds a Axes Visualization
* Adds Rotation Visualization
* Introduces preliminary support Axes and Rotation modification, but not update URDF files in this project
* Adds Color customization for background and gridlines.
and resolves this bug:
https://github.com/ms-iot/vscode-ros/issues/958
=> URDF Rendering Fixes, Axes & Rotation Visualization, Color customization

package-lock.json, package.json, src/build-tool/build-tool.ts, src/build-tool/catkin-tools.ts, src/build-tool/catkin.ts, src/build-tool/colcon.ts, src/build-tool/common.ts, src/debugger/configuration/resolvers/attach.ts, src/extension.ts, src/ros/build-env-utils.ts, src/ros/ros1/core-helper.ts, src/ros/utils.ts
In an attempt to scope when the VSCode extension initialized, there was a race condition which sometimes prevented the environment from loading correctly. Turns out that the scoping had little effect on both the ROS workspace and VSCode itself. Removed the layer of indirection, and added tracing.
=> Remove a layer of indirection causing race condition

src/extension.ts
This small pull request adds the possibility to use the `${workspaceFolder}` variable within the `ros.rosSetupScript` setting.
In case of no clear workspaceFolder, e.g. no active or multliple active workspaces, it warns the user and proceeds with the normal distro discovery. 
This change would allow users from various machine to use the same `ros.rosSetupScript` settings which could point to a local in repository file, simplifying collaboration in case of a more complex setup-script (e.g. sourcing multiple workspaces within a repository ).
=> added ${workspaceFolder} handling to rosSetupScript

README.md
This fixes a few things that were misleading/incorrect when I set this up for debugging a ROS node launched with a ROS 2 XML launch file. The updates assume you are using the pre-release version, because it doesn't work on the standard version.
=> Minor ROS 2 updates for README

src/ros/build-env-utils.ts
This change fix #818. It changes only the configurations that are not already set.
One thing that was not changed is the default C++ standard being at C++14.
=> Fix the `c_cpp_properties.json` configuration overwrite issue (#818)

src/ros/build-env-utils.ts
Create a function that looks up ros version setting and then sets cppStandard variable accordingly ROS1:https://www.ros.org/reps/rep-0003.html
ROS2:https://www.ros.org/reps/rep-2000.html
Fixes:#1288
=> Set cppStandard from ros version
