ms-iot/vscode-ros

package.json, src/constants.ts, src/extension.ts, src/master.ts, src/platformHelper.ts, src/utils.ts
add `rosrun` and `roslaunch` as commands
=> add rosrun and roslaunch as commands

package.json
update package manifest for `ms-riot.vscode-ros`
=> update package manifest

src/master.ts
=> use setInterval to query and update master status repeatedly

CHANGELOG.md, CONTRIBUTING.md, LICENSE, README.md, THIRD_PARTY_NOTICE.md, assets/masterMonitor.js, package.json, src/build.ts, src/catkin-task-provider.ts, src/catkin.ts, src/cpp-formatter.ts, src/debug.ts, src/debugger/debug-session.ts, src/debugger/main.ts, src/extension.ts, src/master.ts, src/platformHelper.ts, src/promise-fs.ts, src/utils.ts, test/index.ts
in preparation for legal review
=> update files based on open source release checklist

package-lock.json, package.json
dependencies updated:
- `mocha`
=> update dependency version

package-lock.json, src/utils.ts
cherry-pick https://github.com/ooeygui/vscode-ros/commit/762fd9e3a3860ab62a44bab73daf40571ebbc40a to fix https://github.com/ms-iot/vscode-ros/issues/40
=> add findPackageFiles() to find all package files correctly

src/extension.ts, src/master.ts, src/utils.ts
`shell: "cmd"` is Windows-specific, needs to be removed for Linux, fix https://github.com/ms-iot/vscode-ros/issues/56
=> remove unnecessary process execution options

package-lock.json, package.json, src/debugger/configuration/providers/ros.ts, src/ros/build-env-utils.ts, src/ros/cli.ts, src/ros/core-helper.ts, src/ros/utils.ts
remove dependency on the `underscore` package and use native JavaScript
=> remove underscore dependency

CHANGELOG.md, package-lock.json, package.json
* update changelog for new version 0.4.4
* update wording for CHANGELOG
* update version number to 0.4.5
=> [release] 0.4.5

README.md
Add documentation for URDF preview and roadmap links
=> Add URDF docs

templates/preview.html
I was not removing the object from the scene which was added. This caused the objects to keep adding instead of updating.
=> Fix Refresh

src/build-tool/build-tool.ts, src/build-tool/catkin-make.ts, src/build-tool/catkin-tools.ts, src/build-tool/colcon.ts, src/extension.ts
This change is to add Colcon build tool support.
=> [build-tools] add support for Colcon build tool

src/urdfPreview/previewManager.ts
=> [telemetry] add telemetry for previewURDF

CHANGELOG.md, README.md, package-lock.json, package.json
remove post-fix in version number, will release after this change gets merged
=> [release] update documentation and version number

src/ros/cli.ts
This change is to address #70.
=> Fix rosrun & roslaunch invocation with undefined.

src/ros/ros2/daemon.ts, src/ros/ros2/ros2.ts
* Add start & stop command support for ROS2 daemon.
* Add ROS2 daemon status bar monitor.
=> [ros2] add `ros2 daemon` status bar monitor & start, stop command support

src/ros/ros2/daemon.ts
use Microsoft copyright header for new code
=> update copyright header

src/extension.ts
addresses https://github.com/ms-iot/vscode-ros/issues/51
=> auto choose ROS distro if only 1 is installed

src/ros/ros1/ros1.ts
the user's .bashrc file will reset the env when vscode create the terminal in linux
=> user .bashrc file will reset the env when vscode create terminal

assets/ros/core-monitor/style.css
Be in favor of `vscode` color scheme over hard-coded.
=> [ROS monitor] In favor of vscode color scheme over hard-coded.

src/build-tool/build-tool.ts, src/debugger/utils.ts, src/extension.ts, src/ros/build-env-utils.ts, src/ros/cli.ts, src/ros/ros1/core-helper.ts, src/ros/ros2/ros2-monitor.ts, src/ros/utils.ts, src/telemetry-helper.ts, src/urdfPreview/previewManager.ts, src/vscode-utils.ts
update package metadata retrieval to decouple vscode context variable from telemetry reporter creation
=> update telemetry reporter creation

src/ros/ros1/core-helper.ts, src/ros/ros2/daemon.ts
display ROS version and distro in status bar item, after the change:
=> display ROS version and distro in status bar item

README.md, package.json, src/extension.ts, src/ros/common/unknown-ros.ts, src/ros/ros.ts, src/ros/ros1/ros1.ts, src/ros/ros2/ros2.ts, src/ros/utils.ts
Add a basic rosdep install command
=> Add rosdep command

src/debugger/configuration/resolvers/launch.ts
After https://github.com/ros/ros_comm/pull/1809 gets merged, the `roslaunch` now outputs the command line in platform-specific format. This pull request is to change the logic accordingly.
This fixes #171.
=> updated launch request for Windows.

.dependabot/config.yml
This config is for automerge config.
=> Adding dependabot config.

package-lock.json, package.json
=> bump the version to 0.6.5-dev for next release.

src/ros/build-env-utils.ts
=> Adding the missing version for cpp properties.

package.json
Implements https://github.com/ms-iot/vscode-ros/issues/441
=> Support Trusted Workspaces

src/debugger/configuration/resolvers/ros1/launch.ts
Implements:
* https://github.com/ms-iot/vscode-ros/issues/452
Fixes:
* https://github.com/ms-iot/vscode-ros/issues/428
* https://github.com/ms-iot/vscode-ros/issues/411
=> Minor fixes to auto-launch, build with debug

.github/workflows/workflow.yml
https://github.com/ms-iot/vscode-ros/issues/902
=> Address Prerelease & Node update
